openapi: "3.0.2"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /:
  /v2:
    get:
      operationId: getVersionDetailsv2
      summary: Show API version details
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json: 
              examples:
                foo:
                  value: {
                    "version": {
                      "status": "CURRENT",
                      "updated": "2011-01-21T11:33:21Z",
                      
          description: |-
            203 response
          content:
            application/json: 
              examples:
                foo:
                  value: {
                    "version": {
                      "status": "CURRENT",
                      "updated": "2011-01-21T11:33:21Z",
                      
                          }
                      ]
                    }
                  }
